version: "3.9"
   
services:
  api:
    build: ./app
    container_name: pz-api
    env_file:
      - .env.dev
    entrypoint: /bin/bash
    command: "./entrypoint.sh"
    volumes:
      - ./app:/app
      - uploads:/archive/data
      - static:/static
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: pz-db
    env_file:
      - .env.dev
    volumes:
      - ./data/db:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    container_name: pz-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - uploads:/archive/data
      - static:/static
    depends_on:
      - api
volumes:
  static:
  uploads:
