version: "3.9"
   
services:
  db:
    image: postgres
    container_name: pz-db
    env_file:
      - .env.dev
    volumes:
      - ./data/db:/var/lib/postgresql/data
  api:
    build: ./app
    container_name: pz-api
    env_file:
      - .env.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    container_name: pz-nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api